{{- if and .Values.ingress.enabled .Values.swagger.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persons-finder.fullname" . }}-basic-auth
  labels:
    {{- include "persons-finder.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.swagger.basicAuth.password | b64enc }}
{{- end }}
